spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
# for production environment, this variable should be validate
spring.jpa.hibernate.ddl-auto=create-drop

spring.datasource.url = jdbc:postgresql://pgserver:5432/postgres
spring.datasource.username = user
spring.datasource.password = password

spring.jpa.show-sql=true

# Kafka bootstrap servers
spring.kafka.bootstrap-servers=kafka:9092

# Producer configuration (for sending JSON objects)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer configuration (for consuming JSON objects)
spring.kafka.consumer.group-id=tascaeats-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

logging.level.org.springframework=INFO
logging.level.com.mkyong=INFO
logging.level.com.zaxxer=DEBUG
logging.level.root=ERROR


spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

logging.pattern.console=%-5level %logger{36} - %msg%n

# Remover no final do projeto
spring.sql.init.mode=always 
spring.jpa.defer-datasource-initialization=true 