spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.datasource.url=jdbc:postgresql://pgserver:5432/deliverydb
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=kafka:9092

# Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer configuration
spring.kafka.consumer.group-id=delivery-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

logging.level.org.springframework=INFO
logging.level.com.zaxxer=DEBUG
logging.level.root=INFO

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

logging.pattern.console=%-5level %logger{36} - %msg%n

server.port=8081

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true